server:
  port: 8082

spring:
  application:
    name: login-service-with-jwt
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false

  jwt:
    jwtSecretKey: ${JWT_SECRET_KEY}
    jwtExpirationTime: ${JWT_EXPIRATION}

  login:
    credentials:
      adminUsername: ${ADMIN_USERNAME}
      adminPassword: ${ADMIN_PASSWORD}
      userUsername: ${USER_USERNAME}
      userPassword: ${USER_PASSWORD}
